- Calendar:
    - " ":
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 10
          showTime: true
          timezone: America/Denver
          integrations:
            - type: sonarr
              service_group: Media Stack
              service_name: Sonarr
              color: teal
            - type: radarr
              service_group: Media Stack
              service_name: Radarr
              color: teal
            - type: ical
              url: https://calendar.google.com/calendar/ical/jeearle%40gmail.com/private-b8b8a770c8ef9aa064fb552e6d61b376/basic.ics
              name: My Events
              color: zinc
              params:
                showName: true

