mqtt:
  host: mosquitto
  user: frigate
  password: 7uafnvp980kdv4
  topic_prefix: frigate

go2rtc:
  streams:
    reolink_doorbell:
      - rtsp://admin:ACDvN8sHNBb7Rj@192.168.0.227:554/
cameras:
  reolink_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://admin:ACDvN8sHNBb7Rj@192.168.0.227:554/h264Preview_01_main
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 3
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 3
        pre_capture: 5
        post_capture: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - package
        - car

      filters:
        person:
          mask: 0.078,0.576,0.124,0.567,0.13,0.665,0.082,0.666
    zones:
      OnProperty:
        coordinates: 
          0.001,0.999,0,0.683,0.146,0.647,0.314,0.64,0.519,0.647,0.759,0.641,1,0.621,1,0.998
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - package
      Street:
        coordinates: 
          0,0.647,0.161,0.635,0.291,0.629,0.438,0.632,0.506,0.635,0.959,0.617,0.954,0.589,0.316,0.594,0.157,0.595
        loitering_time: 0
    review:
      alerts:
        required_zones: OnProperty
      detections:
        required_zones: OnProperty
    motion:
      mask: 0.019,0.625,0.156,0.586,0.995,0.585,0.997,0.002,0,0.004,0.003,0.642
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.16-0
detect:
  enabled: true
